import { collection, query, where, getDocs, addDoc, serverTimestamp } from 'firebase/firestore'
import { db } from '../firebase'
import toast from 'react-hot-toast'

/**
 * Generate missing invoices for completed jobs
 * This ensures all completed jobs have corresponding invoices in reports
 */
export const generateMissingInvoices = async (jobs = []) => {
  try {
    if (!jobs || jobs.length === 0) {
      toast.error('No jobs provided')
      return { success: false, created: 0, failed: 0 }
    }

    let created = 0
    let failed = 0
    const completedJobs = jobs.filter(j => ['completed', 'verified'].includes(j.status))

    for (const job of completedJobs) {
      try {
        // Check if invoice already exists for this job
        const existingInvoice = await getDocs(
          query(collection(db, 'invoices'), where('jobId', '==', job.id))
        )

        if (existingInvoice.docs.length > 0) {
          // Invoice already exists, skip
          continue
        }

        // Create default invoice for this job
        const billNo = `FAC-${Date.now()}`
        const defaultAmount = 500 // Default amount if not specified

        const invoiceData = {
          billNo,
          jobId: job.id || '',
          customerName: job.customerName || 'N/A',
          customerPhone: job.customerPhone || 'N/A',
          customerAddress: job.customerAddress || 'N/A',
          technicianId: job.technicianId || '',
          technicianName: job.technicianName || 'N/A',
          serviceType: job.serviceType || 'N/A',
          components: [],
          totalAmount: defaultAmount,
          discountType: 'percentage',
          discountValue: 0,
          discountAmount: 0,
          billAmount: defaultAmount,
          amountReceived: 0,
          paymentPending: defaultAmount,
          paymentStatus: 'Pending',
          modeOfPayment: 'Cash',
          invoiceDate: new Date().toLocaleDateString('en-IN', { day: '2-digit', month: '2-digit', year: 'numeric' }),
          submittedByTechnician: false,
          adminViewed: false,
          updatedToAdmin: true,
          generatedDate: serverTimestamp(),
          invoiceNumber: billNo,
          createdAt: serverTimestamp(),
          isAutoGenerated: true, // Flag to indicate auto-generated invoice
        }

        await addDoc(collection(db, 'invoices'), invoiceData)
        created++
      } catch (err) {
        console.error(`Failed to create invoice for job ${job.id}:`, err)
        failed++
      }
    }

    if (created > 0) {
      toast.success(`✅ Created ${created} missing invoice(s)`)
    }

    return { success: true, created, failed }
  } catch (err) {
    console.error('Error in generateMissingInvoices:', err)
    toast.error('Failed to generate invoices')
    return { success: false, created: 0, failed: jobs.length }
  }
}

/**
 * Get all jobs that don't have invoices
 */
export const getJobsWithoutInvoices = async (jobs = []) => {
  try {
    const jobsWithoutInvoices = []

    for (const job of jobs) {
      const existingInvoice = await getDocs(
        query(collection(db, 'invoices'), where('jobId', '==', job.id))
      )

      if (existingInvoice.docs.length === 0) {
        jobsWithoutInvoices.push(job)
      }
    }

    return jobsWithoutInvoices
  } catch (err) {
    console.error('Error getting jobs without invoices:', err)
    return []
  }
}
